domain: davidlwatsonjr.github.io
url: https://davidlwatsonjr.github.io
baseurl: /blog/
name: 'David.Writes(&quot;&lt;Code&gt;&quot;);'
description: 'Don&#039;t mind me... just here to take over the world...'
